# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  common-executor:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo


jobs:
  check-mirrors:
    executor: common-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python check.py > README.md

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/repo
          paths:
            - '*'

  commit-readme:
    executor: common-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: 'pwd'
      - run: 'ls'

workflows:
  version: 2
  commit:
    jobs:
      - check-mirrors
      - commit-readme:
          requires:
            - check-mirrors
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check-mirrors
      - commit-readme:
          requires:
            - check-mirrors
